# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  tensorboard_logdir: /storage/czw/tensorboard

checkpoint:
  save_interval_updates: 2500
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 6000 
  normalize: true
  sample_rate: 2048

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 64
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  #loss_weights: [0.1, 10]
  loss_weights: [0.1, 0]

optimization:
  max_update: 40000
  lr: [0.005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-03
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 3200

model:
  _name: wav2vec2
  extractor_mode: layer_norm
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
  conv_feature_layers: '[(512, 10, 5)] + [(512, 3, 2)] * 1 + [(512,3,1)] * 3 + [(512,2,2)] + [(512,2,2)]'
